# Generated by Django 5.1.1 on 2024-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maker',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
